// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace _CodeGenerator.App.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using _CodeGenerator.Definitions.Syntax;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class SyntaxNodeTemplate : SyntaxNodeTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n// Generated by: SyntaxNodeTemplate.tt\r\n\r\nusing Microsoft.VisualStudio.Text;\r\nu" +
                    "sing System.Collections.Generic;\r\nusing System.Linq;\r\n\r\n\r\nnamespace ");
            
            #line 15 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassInfo.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\t// ");
            
            #line 17 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SyntaxPart.GetType().BaseType.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\tpublic partial class ");
            
            #line 18 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassInfo.Name));
            
            #line default
            #line hidden
            this.Write(" : ISyntaxNode\r\n\t{\r\n\t\tpublic Span Span { get; }\r\n");
            
            #line 21 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"

	switch (this.SyntaxPart)
    {
		case SyntaxList sl:
			
            
            #line default
            #line hidden
            this.Write("\t\t/***** SyntaxList *****/\r\n\r\n\t\tprivate I");
            
            #line 28 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sl.Name));
            
            #line default
            #line hidden
            this.Write("Content[] content;\r\n\t\t\r\n\t\tpublic ");
            
            #line 30 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sl.GetType().Name));
            
            #line default
            #line hidden
            this.Write("(IList<I");
            
            #line 30 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sl.Name));
            
            #line default
            #line hidden
            this.Write("Content> content)\r\n\t\t{\r\n\t\t\tthis.content = content.ToArray();\r\n\t\t}\r\n\r\n\t\t\t");
            
            #line 35 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"

			break; // case SyntaxList sl

		case DelimitedTextSyntax dts:
			
            
            #line default
            #line hidden
            this.Write("\t\t/***** DelimitedText *****/\r\n\t\tpublic ");
            
            #line 41 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dts.GetType().Name));
            
            #line default
            #line hidden
            this.Write("List Contents { get; }\r\n\r\n\t\tpublic ");
            
            #line 43 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dts.GetType().Name));
            
            #line default
            #line hidden
            this.Write("(IList<I");
            
            #line 43 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassInfo.Name));
            
            #line default
            #line hidden
            this.Write("Content> contents)\r\n\t\t{\r\n\t\t\tthis.Contents = new ");
            
            #line 45 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dts.GetType().Name));
            
            #line default
            #line hidden
            this.Write("List(contents);\r\n\t\t}\r\n\r\n\t\t\t");
            
            #line 48 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"

			break; // case DelimitedTextSyntax dts

		case Stream stream:
			
            
            #line default
            #line hidden
            this.Write("\t\t/***** Stream *****/\r\n\t\tpublic ");
            
            #line 54 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(stream.GetType().Name));
            
            #line default
            #line hidden
            this.Write("Tokens Tokens { get; }\r\n\r\n\t\tpublic ");
            
            #line 56 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassInfo.Name));
            
            #line default
            #line hidden
            this.Write("(IList<I");
            
            #line 56 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(stream.ContentList.GetType().Name));
            
            #line default
            #line hidden
            this.Write("Content> tokens)\r\n\t\t{\r\n\t\t\tthis.Tokens = new ");
            
            #line 58 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(stream.GetType().Name));
            
            #line default
            #line hidden
            this.Write("Tokens(tokens);\r\n\t\t\tthis.Span = this.Tokens.Span;\r\n\t\t}\r\n\r\n\t\t\t");
            
            #line 62 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"

			break; // case Stream stream

		case Syntax syntax:
			
            
            #line default
            #line hidden
            this.Write("\t\t/***** Syntax *****/\r\n\t\t\t");
            
            #line 68 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"


			foreach (var part in syntax.Combinations.SelectMany(x => x.Parts).Distinct(new SyntaxPartComparer()))
            { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 73 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(part.GetType().Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 73 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(part.Name));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n\r\n\t\t\t");
            
            #line 75 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"

            }

			foreach (var combination in syntax.Combinations)
            { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 81 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(syntax.GetType().Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 81 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(
					", ",
					combination
					.Parts
					.Select(x => x.GetType().Name + " " + x.Name))));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n");
            
            #line 89 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"

				foreach (var part in combination.Parts)
                { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\tthis.");
            
            #line 93 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(part.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 93 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(part.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t");
            
            #line 94 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"

                }
				
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\t}\r\n\r\n\t\t\t");
            
            #line 100 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"

            }
			
			break; // case Syntax s

		case Token token:
			
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic string Text { get; }\r\n\r\n\t\tpublic ");
            
            #line 110 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(token.GetType().Name));
            
            #line default
            #line hidden
            this.Write("(RawToken rt)\r\n\t\t{\r\n\t\t\tthis.Span = rt.Span;\r\n\t\t\tthis.Text = rt.Text;\r\n\t\t}\r\n\r\n\t\t\t");
            
            #line 116 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"

			break; // case Token token

		case DynamicToken dToken:
			
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic string Text { get; }\r\n\r\n\t\tpublic ");
            
            #line 124 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dToken.GetType().Name));
            
            #line default
            #line hidden
            this.Write("(RawToken rt)\r\n\t\t{\r\n\t\t\tthis.Span = rt.Span;\r\n\t\t\tthis.Text = rt.Text;\r\n\t\t}\r\n\r\n\t\t\t");
            
            #line 130 "C:\Dev\T4TW\_CodeGenerator.App\Templates\SyntaxNodeTemplate.tt"

			break; // case DynamicToken dToken

    }
	
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class SyntaxNodeTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
