
// Generated by: SyntaxNodeTemplate.tt

using Microsoft.VisualStudio.Text;
using System.Collections.Generic;
using System.Linq;


namespace T4TW.Syntax
{
	// Token
	public partial class ClassFeatureBlockOpenTagToken : ISyntaxNode
	{
		public Span Span { get; }

		public string Text { get; }

		public ClassFeatureBlockOpenTagToken(RawToken rt)
		{
			this.Span = rt.Span;
			this.Text = rt.Text;
		}

			
	}
}