
// Generated by: SyntaxNodeTemplate.tt

using Microsoft.VisualStudio.Text;
using System.Collections.Generic;
using System.Linq;


namespace T4TW.Syntax
{
	// Stream
	public partial class ControlBlockStream : ISyntaxNode
	{
		public Span Span { get; }
		/***** Stream *****/
		public ControlBlockStreamTokens Tokens { get; }

		public ControlBlockStream(IList<IControlBlockStreamListContent> tokens)
		{
			this.Tokens = new ControlBlockStreamTokens(tokens);
			this.Span = this.Tokens.Span;
		}

			
	}
}