
// Generated by: ContentInterfaceTemplate.tt

namespace T4TW.Syntax
{

	public interface IControlBlockStreamListContent : ISyntaxNode { }


	partial class SourceCodeToken : IControlBlockStreamListContent { }
}