
// Generated by: ContentInterfaceTemplate.tt

namespace T4TW.Syntax
{

	public interface IDirectiveSyntaxListContent : ISyntaxNode { }


	partial class DirectiveSyntax : IDirectiveSyntaxListContent { }
}