
// Generated by: SyntaxNodeTemplate.tt

using Microsoft.VisualStudio.Text;
using System.Collections.Generic;
using System.Linq;


namespace T4TW.Syntax
{
	// Syntax
	public partial class DirectiveParameterSyntax : ISyntaxNode
	{
		public Span Span { get; }
		/***** Syntax *****/
			
		public IdentifierToken Identifier { get; }

			
		public EqualsToken EqualsToken { get; }

			
		public StringLiteral ParameterValue { get; }

			
		public DirectiveParameterSyntax(IdentifierToken Identifier, EqualsToken EqualsToken, StringLiteral ParameterValue)
		{

				this.Identifier = Identifier;
				
				this.EqualsToken = EqualsToken;
				
				this.ParameterValue = ParameterValue;
						
		}

			
	}
}