
// Generated by: SyntaxNodeTemplate.tt

using Microsoft.VisualStudio.Text;
using System.Collections.Generic;
using System.Linq;


namespace T4TW.Syntax
{
	// Syntax
	public partial class DirectiveSyntax : ISyntaxNode
	{
		public Span Span { get; }
		/***** Syntax *****/
			
		public DirectiveBlockTagOpenToken StartToken { get; }

			
		public DirectiveContentsSyntax Contents { get; }

			
		public BlockTagCloseToken EndToken { get; }

			
		public DirectiveSyntax(DirectiveBlockTagOpenToken StartToken, DirectiveContentsSyntax Contents, BlockTagCloseToken EndToken)
		{

				this.StartToken = StartToken;
				
				this.Contents = Contents;
				
				this.EndToken = EndToken;
						
		}

			
	}
}