
// Generated by: ContentInterfaceTemplate.tt

namespace T4TW.Syntax
{

	public interface IDirectiveParameterSyntaxListContent { }


	partial class DirectiveParameterSyntax : IDirectiveParameterSyntaxListContent { }
}