
// Generated by: SyntaxNodeTemplate.tt

using Microsoft.VisualStudio.Text;
using System.Collections.Generic;
using System.Linq;


namespace T4TW.Syntax
{
	// _CodeGenerator.Definitions.Syntax.SyntaxList
	public partial class DirectiveSyntaxList : ISyntaxNode
	{
		public Span Span { get; }
		/***** SyntaxList *****/

		private IDirectiveSyntaxListContent[] content;
		
		public DirectiveSyntaxList(IList<IDirectiveSyntaxListContent> content)
		{
			this.content = content.ToArray();
		}

			
	}
}