
// Generated by: SyntaxNodeTemplate.tt

using Microsoft.VisualStudio.Text;
using System.Collections.Generic;
using System.Linq;


namespace T4TW.Syntax
{
	// Syntax
	public partial class DirectiveParameterIdentifierSyntax : ISyntaxNode
	{
		public Span Span { get; }
		/***** Syntax *****/
			
		public IdentifierToken ParameterIdentifierToken { get; }

			
		public DirectiveParameterIdentifierSyntax(IdentifierToken ParameterIdentifierToken)
		{

				this.ParameterIdentifierToken = ParameterIdentifierToken;
						
		}

			
	}
}