
// Generated by: ContentInterfaceTemplate.tt

namespace T4TW.Syntax
{

	public interface IStaticTextSyntaxListContent : ISyntaxNode { }


	partial class TemplateTextToken : IStaticTextSyntaxListContent { }
}