
// Generated by: ContentInterfaceTemplate.tt

namespace T4TW.Syntax
{

	public interface IStringLiteralTextListContent : ISyntaxNode { }


	partial class StringLiteralTextToken : IStringLiteralTextListContent { }
}