
// Generated by: SyntaxNodeTemplate.tt

using Microsoft.VisualStudio.Text;
using System.Collections.Generic;
using System.Linq;


namespace T4TW.Syntax
{
	// Syntax
	public partial class StringLiteral : ISyntaxNode
	{
		public Span Span { get; }
		/***** Syntax *****/
			
		public StringDelimiterToken StartToken { get; }

			
		public StringLiteralText Text { get; }

			
		public StringDelimiterToken EndToken { get; }

			
		public StringLiteral(StringDelimiterToken StartToken, StringLiteralText Text, StringDelimiterToken EndToken)
		{

				this.StartToken = StartToken;
				
				this.Text = Text;
				
				this.EndToken = EndToken;
						
		}

			
	}
}