
// Generated by: ContentInterfaceTemplate.tt

namespace T4TW.Syntax
{
	public interface ITemplateBodySyntaxContent : ISyntaxNode { }

	partial class StaticTextSyntax : ITemplateBodySyntaxContent { }

	partial class ControlBlock : ITemplateBodySyntaxContent { }

	partial class DirectiveSyntax : ITemplateBodySyntaxContent { }
}