
// Generated by: SyntaxNodeTemplate.tt

using Microsoft.VisualStudio.Text;
using System.Collections.Generic;
using System.Linq;


namespace T4TW.Syntax
{
	// _CodeGenerator.Definitions.Syntax.Syntax
	public partial class TemplateSyntax : ISyntaxNode
	{
		public Span Span { get; }
		/***** Syntax *****/
			
		public DirectiveSyntaxList Directives { get; }

			
		public TemplateBodySyntax TemplateBody { get; }

			
		public TemplateSyntax(DirectiveSyntaxList Directives, TemplateBodySyntax TemplateBody)
		{

				this.Directives = Directives;
				
				this.TemplateBody = TemplateBody;
						
		}

			
		public TemplateSyntax()
		{
		
		}

			
	}
}