
// Generated by: SyntaxNodeTemplate.tt

using Microsoft.VisualStudio.Text;
using System.Collections.Generic;
using System.Linq;


namespace T4TW.Syntax
{
	// DelimitedTextSyntax
	public partial class TemplateBodySyntax : ISyntaxNode
	{
		public Span Span { get; }
		/***** DelimitedText *****/
		public TemplateBodySyntaxList Contents { get; }

		public TemplateBodySyntax(IList<ITemplateBodySyntaxContent> contents)
		{
			this.Contents = new TemplateBodySyntaxList(contents);
		}

			
	}
}