
// Generated by: ContentInterfaceTemplate.tt

namespace T4TW.Syntax
{

	public interface ITemplateBodySyntaxListContent { }


	partial class StaticTextSyntax : ITemplateBodySyntaxListContent { }

	partial class ControlBlock : ITemplateBodySyntaxListContent { }
}